# Generated by Django 3.2.6 on 2021-08-31 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210830_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domiciolio',
            new_name='Domicilio',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='domiciolio',
            new_name='domicilio',
        ),
    ]
